export const invoices = [
  {
    name: "Lucas",
    paymentStatus: "Paid",
    // totalAmount: 250,
    change: 50,
    s1: 20.2,
    s2: 0,
  },
  {
    name: "Emma",
    paymentStatus: "Pending",
    // totalAmount: 100,
    change: 20,
    s1: 156.2,
    s2: 100,
  },
  {
    name: "Elton",
    paymentStatus: "Unpaid",
    // totalAmount: 375,
    change: 30,
    s1: -25.1,
    s2: 100,
  },
  {
    name: "Eddie",
    paymentStatus: "Paid",
    // totalAmount: 40,
    change: -50,
    s1: 11.5,
    s2: 100,
  },
  {
    name: "Grace",
    paymentStatus: "Paid",
    // totalAmount: 550,
    change: -100,
    s1: -46.4,
    s2: 100,
  },
  {
    name: "Fiona",
    paymentStatus: "Pending",
    // totalAmount: 70,
    change: -200,
    s1: 5.5,
    s2: 100,
  },
  {
    name: "Harley",
    paymentStatus: "Unpaid",
    // totalAmount: 90,
    change: 300,
    s1: -46.6,
    s2: 100,
  },
  {
    name: "Ethan",
    paymentStatus: "Unpaid",
    // totalAmount: 90,
    change: 100,
    s1: -44,
    s2: 100,
  },
];
